// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtvepdwfotsgcfqcppmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dmVwZHdmb3RzZ2NmcWNwcG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDQ5MTEsImV4cCI6MjA2MDk4MDkxMX0.O_j4a1MloVp6CWh--zILiwzqTwwIvBPOhHWe1kkxLHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);