// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmmeipvqmshlxfynrnrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tbWVpcHZxbXNobHhmeW5ybnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMjcyOTEsImV4cCI6MjA2MDgwMzI5MX0.JxB2phn6aYpiBJlwbyaifhKV7d9xVRlU3o565DA1SEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);