// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyvmfhkihioqshuzzziz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5dm1maGtpaGlvcXNodXp6eml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDE3MzMsImV4cCI6MjA2MDk3NzczM30.w6kl3PP8eUW0pOz-ZfpDunA1Yd5e9CoYlrIl79su1cs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);